

services:
  postgres:
    image: postgres:15-alpine
    container_name: bkhrease-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bkhrease_strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bkhrease-network

  adminer:
    image: adminer:latest
    container_name: bkhrease-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - bkhrease-network
    depends_on:
      - postgres



volumes:
  postgres_data:

networks:
  bkhrease-network:
    driver: bridge
